import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { runInNewContext } from 'node:vm';
import { assertCompletedModelResponse, collectFinalModelText, parseModelValue } from '../server/remediationOutput.js';
import { generatePatch } from '../server/wordpressPatchV2Hook.js';
import { registerRoutes, deterministicMetaDescription } from '../server/wordpressSeoAdapterV2Hook.js';
import { validateSeoSuggestion } from './editorialQuality.js';
import { contentSafetyErrors } from './editorialContentSafety.js';
import { extractLinkEvidence, assessLinkEvidenceHtml } from '../server/linkEvidenceHook.js';
import { resolutionPath, correctionMatchesProblem, shouldOpenAutomaticProposal } from './resolutionPath.js';
import { brokenExternalTarget, prepareElementorBrokenExternalLink, removeExactAnchor, setBrokenLinkCleanupMode } from './brokenLinkRemediation.js';

const source='https://example.com/pagina/', target='https://www.yogajournal.com/poses/types/advanced/';
const meta='Scopri come integrare lo yoga in una routine equilibrata con posizioni, consigli pratici e indicazioni utili per iniziare in modo graduale e consapevole.';
const words=Array.from({length:230},(_,n)=>`concetto${String.fromCharCode(97+Math.floor(n/26))}${String.fromCharCode(97+n%26)}`);
const original=`<p>${words.slice(0,176).join(' ')}.</p>`, expanded=`<p>${words.join(' ')}.</p>`;
const page={url:source,title:'Guide pratiche per lo yoga',content:original,remediationMeasurement:{frontendWords:176,fieldWords:176,minimumWords:180}};
const request={topic:'Remediation WordPress content',context:JSON.stringify({page,issue:{type:'thin',label:'Contenuto breve: 176 parole'}})};
const routes=new Map();registerRoutes({post:(path,handler)=>routes.set(path,handler)});
const seo=async body=>{const res={statusCode:200,status(code){this.statusCode=code;return this;},json(body){this.body=body;return this;}};await routes.get('/api/wordpress/generate-seo-value-v2')({body,ip:'resolution-fixture'},res);return res;};
function fixture(t,responses){
 const old={OPENAI_API_KEY:process.env.OPENAI_API_KEY,OPENAI_MONTHLY_BUDGET_USD:process.env.OPENAI_MONTHLY_BUDGET_USD};process.env.OPENAI_API_KEY='fixture-only';process.env.OPENAI_MONTHLY_BUDGET_USD='100';
 t.after(()=>{for(const[k,v]of Object.entries(old)){if(v===undefined)delete process.env[k];else process.env[k]=v;}});
 let ledger; t.mock.method(fs,'readFile',async()=>{if(!ledger)throw Object.assign(new Error('missing'),{code:'ENOENT'});return ledger;});
 t.mock.method(fs,'mkdir',async()=>{});t.mock.method(fs,'writeFile',async(_p,v)=>{ledger=v;});t.mock.method(fs,'rename',async()=>{});
 const calls=[];t.mock.method(globalThis,'fetch',async(url,init)=>{assert.match(String(url),/api\.openai\.com\/v1\/responses$/);calls.push(JSON.parse(init.body));return Response.json(responses[Math.min(calls.length-1,responses.length-1)]);});return calls;
}
for(const[name,data]of[
 ['Responses',{status:'completed',output:[{type:'message',role:'assistant',content:[{type:'output_text',text:JSON.stringify({value:expanded})}]}]}],
 ['chat',{choices:[{finish_reason:'stop',message:{content:JSON.stringify({value:expanded})}}]}],
 ['fenced parts',{choices:[{finish_reason:'stop',message:{content:[{type:'text',text:'```json\n'+JSON.stringify({value:expanded})+'\n```'}]}}]}],
])test('actual content generator accepts complete '+name,async t=>{const calls=fixture(t,[data]);const result=await generatePatch(request);assert.equal(result.changes.content,expanded);assert.equal(result.quality.publishable,true);assert.equal(calls.length,1);assert.equal(calls[0].text.format.strict,true);});
test('format retry is bounded and can recover',async t=>{const calls=fixture(t,[{status:'completed',output_text:'not-json'},{status:'completed',output_text:JSON.stringify({value:expanded})}]);assert.equal((await generatePatch(request)).changes.content,expanded);assert.equal(calls.length,2);});
test('malformed JSON remains blocked after retry',async t=>{const calls=fixture(t,[{status:'completed',output_text:'{"value":"unfinished'}]);await assert.rejects(generatePatch(request),e=>e.code==='AI_OUTPUT_FORMAT');assert.equal(calls.length,2);});
for(const data of[
 {status:'incomplete',output_text:'{"value":"valid but partial"}'},
 {status:'completed',incomplete_details:{reason:'max_output_tokens'}},
 {choices:[{finish_reason:'length',message:{content:'{"value":"partial"}'}}]},
 {choices:[{finish_reason:'stop',message:{refusal:'no'}}]},
 {choices:[{finish_reason:'content_filter',message:{content:'filtered'}}]},
 {choices:[{finish_reason:'tool_calls',message:{content:'not final'}}]},
 {output:[{type:'message',content:[{type:'refusal',refusal:'no'}]}]},
])test('incomplete/refused response cannot become a proposal '+JSON.stringify(data),()=>assert.throws(()=>assertCompletedModelResponse(data),e=>/^AI_/.test(e.code)));
test('refusal stops retries and never selects a fallback',async t=>{const calls=fixture(t,[{choices:[{finish_reason:'stop',message:{refusal:'no'}}]}]);const result=await seo({kind:'meta_description',page:{content:meta}});assert.equal(result.body.code,'AI_REFUSAL');assert.equal(result.body.publishable,false);assert.equal(calls.length,1);});
test('reasoning and wrong JSON shapes are not values',()=>{assert.equal(collectFinalModelText({output:[{type:'reasoning',content:[{type:'output_text',text:'private'}]}]}),'');for(const value of['{"value":22}','{"value":["text"]}','{"value":"text","extra":true}','[{"value":"text"}]','prose {"value":"text"} prose','<p>not JSON</p>'])assert.throws(()=>parseModelValue(value),e=>e.code==='AI_OUTPUT_FORMAT');});
test('fallback never clips a repeated generated excerpt',()=>{const title='Yoga per dimagrire la guida';const excerpt=`${title} ${title} Introduzione: un percorso [&hellip;]`;assert.equal(deterministicMetaDescription({title,excerpt,content:'Testo breve.'}),'');assert.equal(deterministicMetaDescription({title,excerpt,content:`<h1>${title}</h1><p>${meta}</p>`}),meta);assert.equal(deterministicMetaDescription({content:'Parole '.repeat(60)}),'');});
test('manual metadata uses the same quality gate without another AI request',async t=>{const calls=fixture(t,[{status:'completed',output_text:'{"value":"Yoga per dimagrire la guida yoga per dimagrire la guida per"}'}]);const failed=await seo({kind:'meta_description',page:{title:'Yoga per dimagrire la guida',content:'Breve.'}});assert.equal(failed.statusCode,422);assert.equal(calls.length,3);const valid=await seo({kind:'meta_description',page:{content:meta},manualValue:meta});assert.equal(valid.body.value,meta);assert.equal(valid.body.manual,true);assert.equal(valid.body.quality.source,'user-reviewed');assert.equal(valid.body.approvalToken,undefined);for(const manualValue of['incompleto per','x'.repeat(161),`<b>${meta}</b>`])assert.equal((await seo({kind:'meta_description',page:{content:meta},manualValue})).statusCode,422);assert.equal(calls.length,3);});
test('manual body still enforces length, HTML safety and source bounds',async t=>{const calls=fixture(t,[]);const valid=await generatePatch({...request,manualValue:expanded});assert.equal(valid.manual,true);assert.equal(valid.changes.content,expanded);await assert.rejects(generatePatch({...request,manualValue:original}),e=>e.code==='EDITORIAL_REVIEW_REQUIRED');await assert.rejects(generatePatch({...request,manualValue:expanded+'<script>alert(1)</script>'}),e=>e.code==='EDITORIAL_REVIEW_REQUIRED');assert.equal(calls.length,0);});
for(const html of['<p onclick="alert(1)">testo.</p>','<p><a href="javascript:alert(1)">testo</a>.</p>','<p><a href="jav&#x61;script:alert(1)">testo</a>.</p>','<iframe src="https://evil.example"></iframe>','<svg onload="alert(1)"></svg>','<p>testo <strong>aperto.</p>','<h1>Nuovo titolo</h1>','<p style="background:url(https://evil.example)">testo.</p>'])test('unsafe content is blocked '+html,()=>assert.equal(validateSeoSuggestion('content',html).publishable,false));
test('body markup is not allowed in metadata and content cannot remove links',()=>{const previous='<p>Leggi la <a href="https://example.com/guida/">guida</a> per approfondire.</p>';assert.deepEqual(contentSafetyErrors(previous+'<h2>Approfondimenti</h2><p>Altre indicazioni.</p>',previous),[]);assert.ok(contentSafetyErrors('<p>Testo senza il collegamento.</p>',previous).length);assert.equal(validateSeoSuggestion('meta_description','<p>'+meta+'</p>').publishable,false);});
const html=body=>`<!doctype html><html><head><title>Pagina yoga</title></head><body><main><p>${meta}</p>${body}</main></body></html>`;
test('evidence matches hrefs and supported wrappers, not mentions',()=>{const doc=html(`<a data-href="${target}" href="https://other.example/">altro</a><!-- <a href="${target}">commento</a> --><a href="https://www.google.com/search?q=${target}">Yoga Journal</a>`);const e=extractLinkEvidence(doc,source,target);assert.equal(e.occurrenceCount,1);assert.equal(e.anchorText,'Yoga Journal');assert.equal(assessLinkEvidenceHtml(doc,source,source,e),true);});
test('partial, redirected, challenge and login pages cannot prove absence',()=>{for(const[doc,final]of[['<html><body>loading</body></html>',source],[html('').replace('</html>',''),source],[html(''),'https://example.com/other/'],[html('').replace('Pagina yoga','Just a moment'),source],[html('').replace('Pagina yoga','Login'),source]])assert.equal(assessLinkEvidenceHtml(doc,source,final,extractLinkEvidence(doc,final,target)),false);});
test('bounded scan is incomplete rather than a false zero',()=>{const doc=html('<a href="https://other.example">x</a>'.repeat(15001)+`<a href="${target}">target</a>`);const e=extractLinkEvidence(doc,source,target);assert.equal(e.scanComplete,false);assert.equal(assessLinkEvidenceHtml(doc,source,source,e),false);});
const ui=await fs.readFile(new URL('./WordPressLiveRemediationControlV2.jsx',import.meta.url),'utf8');
const code=ui.match(/async function buildPlan\([\s\S]*?(?=\n(?:const |function |async function |export ))/)[0];
const env={URL,pluginMeta:e=>e.meta||{},remediationContextDecision:()=>({allowed:true}),brokenExternalTarget,prepareElementorBrokenExternalLink,removeExactAnchor,ownershipUndetermined:(_k,message)=>new Error(message)};
const plan=runInNewContext(code+'\nbuildPlan',env);
const evidence={targetUrl:target,requestedSourceUrl:source,occurrenceCount:0,verificationSafe:true,scanComplete:true};
const empty={entity:{id:1,meta:{_elementor_data:'[{"id":"text","settings":{"editor":"<p>Testo conservato.</p>"}}]'}}};
test('actual planner sets a native resolved no-op from both sources',async()=>{const result=await plan('external_link',{targetUrl:target},empty,source,{}, {linkEvidence:evidence});assert.equal(result.alreadyResolved,true);assert.equal(result.linkResolution,'absent-confirmed');assert.equal(result.changes,undefined);assert.match(ui,/status: "resolved"[\s\S]*linkResolution: plan\.linkResolution/);assert.match(ui,/const resolved = next\.filter\(\(item\) => item\.status === "resolved"\)/);});
for(const override of[{verificationSafe:false},{scanComplete:false},{occurrenceCount:1},{targetUrl:'https://other.example/'},{requestedSourceUrl:'https://another.example/'}])test('conflicting evidence never closes problem '+JSON.stringify(override),async()=>assert.rejects(plan('external_link',{targetUrl:target},empty,source,{}, {linkEvidence:{...evidence,...override}})));
test('local href plus public zero remains blocked; destructive metadata is exact',async()=>{const raw=JSON.stringify([{id:'w',settings:{editor:`<a href="${target}">Yoga Journal</a>`}}]);const inspected={entity:{meta:{_elementor_data:raw}}};await assert.rejects(plan('external_link',{targetUrl:target},inspected,source,{}, {linkEvidence:evidence}));setBrokenLinkCleanupMode(target,'delete-anchor-text');assert.equal((await plan('external_link',{targetUrl:target},inspected,source,{}, {linkEvidence:{...evidence,occurrenceCount:1}})).linkCleanup.action,'delete-anchor-text');});
test('actual title and description plans forward manual input',async()=>{for(const kind of['title','meta_description']){let received;const build=runInNewContext(code+'\nbuildPlan',{...env,metaKey:()=>[kind==='title'?'rank_math_title':'rank_math_description','Rank Math'],generateSeoValue:async(...args)=>{received=args[4];return{value:args[4],quality:{publishable:true}};}});const result=await build(kind,{}, {entity:{id:42}},source,{}, {manualValue:meta});assert.equal(received,meta);assert.equal(Object.values(result.changes.meta)[0],meta);}});
for(const[p,action]of[[{issueType:'unknown'},'agent'],[{issueType:'keyword',title:'Ottimizza yoga'},'agent'],[{issueType:'duplicate-description',correctability:'automatic'},'prepare'],[{issueType:'duplicate-title',correctability:'automatic',stale:true},'audit'],[{issueType:'duplicate-title',correctability:'automatic',interventionState:'applied',stale:true},'verify'],[{issueType:'lost-response-recovery',correctability:'automatic'},'history'],[{issueType:'url-alias'},'audit'],[{issueType:'image-alt',correctability:'manual'},'manual'],[{issueType:'thin',sourceUrl:'javascript:alert(1)'},'audit']])test('concrete resolution route '+action+' '+p.issueType,()=>{const problem={sourceUrl:source,...p};const path=resolutionPath(problem);assert.equal(path.action,action);assert.ok(path.instructions.length>60);assert.equal(shouldOpenAutomaticProposal(problem),action==='prepare'&&p.correctability==='automatic');});
test('two links on the same page never share correction evidence',()=>{const p={issueType:'broken-external-link',sourceUrl:source,targetUrls:[target]};const c={issueType:p.issueType,sourceUrl:source,issue:{targetUrl:target}};assert.equal(correctionMatchesProblem(p,c),true);assert.equal(correctionMatchesProblem(p,{...c,issue:{targetUrl:'https://other.example/'}}),false);assert.equal(correctionMatchesProblem({...p,targetUrls:[target,'https://other.example/']},c),false);});
